const { Client } = require('pg');

async function testCrypto() {
  const client = new Client({
    host: 'aws-0-ap-southeast-1.pooler.supabase.com',
    port: 5432,
    user: 'postgres.xusudxzoiqcfqxvuerhy',
    password: 'Sw#Hub2026!xKp9z',
    database: 'postgres',
    ssl: { rejectUnauthorized: false }
  });

  await client.connect();
  const res = await client.query("SELECT extensions.crypt('Admin1234!', extensions.gen_salt('bf')) AS hash;");
  console.log('Bcrypt hash generated by Postgres:', res.rows[0].hash);
  await client.end();
}

testCrypto().catch(console.error);
